version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/deal_in_api
    ports:
      - 8080:8080
    image: deal_in:deal_in_api
    container_name: deal_in_client_container
    command: python manage.py runserver 0.0.0.0:8080
